version: "3"
services:
  app:
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    build:
      target: dev
    volumes:
      - .:/app
  db:
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 6543:5432

volumes:
  pg_data:
