version: "3.8"
services:
  app:
    build:
      dockerfile: docker/development.dockerfile
    environment:
      DEV_HOST: "0.0.0.0"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - shards_lib:/app/lib
    ports:
      - 3001:3001 # This is the Lucky watcher reload port

    entrypoint: ["docker/dev_entrypoint.sh"]

  db:
    volumes:
      - pg_data:/var/lib/postgresql
    ports:
      - 6543:5432

volumes:
  pg_data:
  node_modules:
  shards_lib:
