version: "3"
services:
  app:
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    build:
      target: dev
    volumes:
      - .:/app
  db:
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
volumes:
  pg-data:
